PATH_TO_FOLDER_SYSTEM_DATA = 'SystemData/'
PATH_TO_FOLDER_GENERAL_SETTINGS = 'Settings/'
PATH_TO_FOLDER_DOMAINS_SETTINGS = PATH_TO_FOLDER_GENERAL_SETTINGS + 'Domains/'

PATH_TO_FILE_OFFERS_CACHE = PATH_TO_FOLDER_SYSTEM_DATA + 'offers_info_cache.json'
